//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioUnleashed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContributionMedium
    {
        public int MediumType { get; set; }
        public string Caption { get; set; }
        public string Link { get; set; }
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Contribution Contribution { get; set; }
    }
}
