//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioUnleashed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public bool isSeen { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Sender { get; set; }
        public int NotificationType { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> SenderId { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
