//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioUnleashed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Contributions = new HashSet<Contribution>();
            this.ProjectPermissions = new HashSet<ProjectPermission>();
            this.ProjectMedia = new HashSet<ProjectMedium>();
            this.Portfolios = new HashSet<Portfolio>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Template { get; set; }
        public int CollaborationSetting { get; set; }
    
        public virtual ICollection<Contribution> Contributions { get; set; }
        public virtual ICollection<ProjectPermission> ProjectPermissions { get; set; }
        public virtual ICollection<ProjectMedium> ProjectMedia { get; set; }
        public virtual ICollection<Portfolio> Portfolios { get; set; }
    }
}
