//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALUnitTestProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioUnleashedEntities2 : DbContext
    {
        public PortfolioUnleashedEntities2()
            : base("name=PortfolioUnleashedEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContactInfo> ContactInfoes { get; set; }
        public DbSet<Contribution> Contributions { get; set; }
        public DbSet<ContributionMedium> ContributionMediums { get; set; }
        public DbSet<Education> Educations { get; set; }
        public DbSet<Link> Links { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Portfolio> Portfolios { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectMedium> ProjectMediums { get; set; }
        public DbSet<ProjectPermission> ProjectPermissions { get; set; }
        public DbSet<QuickReference> QuickReferences { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
