//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioUnleashed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribution
    {
        public Contribution()
        {
            this.ContributionMedia = new HashSet<ContributionMedium>();
        }
    
        public int UserId { get; set; }
        public int ProjectId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ContributionMedium> ContributionMedia { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
