//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioUnleashed
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public UserSetting()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool IsPublic { get; set; }
        public bool IsEmailedForAdminMessage { get; set; }
        public bool IsEmailedForCollaborationAddition { get; set; }
        public bool IsEmailedForCollaborationRemoval { get; set; }
        public bool IsEmailedForCollaborationRequest { get; set; }
        public bool IsEmailedForViewReport { get; set; }
        public bool IsEmailedForGlobalAccouncement { get; set; }
        public bool IsEmailedForLeaveCard { get; set; }
        public bool IsEmailedForPortfolioFeedback { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
